Algoritmo "semnome"

Var

   n1,n2,m : real


Inicio

      escreva (" Informe sua primeira nota: ")
      leia (n1)
      escreva (" Informe sua segunda nota: ")
      leia (n2)
      
      m <- (n1+n2) / 2
      
      escreva ( "Sua média é: ", m )

      se (m >= 7) entao
         escreva (". Você foi aprovado! ")
      senao
           escreva (". Você não foi aprovado. ")
      fimse
      

Fimalgoritmo